name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.2
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^8.0.0
  injectable: ^2.4.4
  
  # Navigation
  go_router: ^14.2.1
  
  # Network
  dio: ^5.5.0+1
  connectivity_plus: ^6.0.5
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  
  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  flutter_polyline_points: ^2.1.0
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  
  # Notifications
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.3
  
  # Charts
  fl_chart: ^0.68.0
  
  # UI/Utils
  signature: ^5.5.0
  intl: 0.20.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.11
  dartz: ^0.10.1 
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0
  image_picker: ^1.2.1

  uuid: any
  mobile_scanner: ^5.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1
  
  # Testing
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
